### PR TITLE
Startup backend and redesign

### PR DESCRIPTION
**Pull request by realStandal**

### CODE REVIEW

**Comment by realStandal** [comment]
CC @cannikin - Though, it may just work without any added steps (maybe because I have merge access?)

**Comment by noire-munich** [comment]
> It did! I just need admin on the user I created: `standal`. I take it the preview uses the same database as `main`? (it's already been migrated, whoops)

Access granted :+1:

**Comment by cannikin** [comment]
We could do some fancy stuff with .env vars to have PRs run against a separate database, but I wouldn’t worry about it until post launch.

**Comment by realStandal** [comment]
@noire-munich @cannikin Y'all rock, much appreciated!

**Pull request merged**
