### PR TITLE
fix bg-img

### PR DESCRIPTION
**Pull request by KrisCoulson**

### CODE REVIEW

**Comment by peterp** [comment]
@KrisCoulson This looks good to me, but I hadn't noticed the original problem?

**Comment by pavelloz** [comment]
The problem this PR tries to solve I kind of described in my try of tackling it: https://github.com/redwoodjs/sprout/pull/39

But i think there is something wrong with `h-full` right now, because until the image is loaded, no vertical space is reserved and content is jumping around with the word "forest" (missing alt, so probably browser is using filename) in the top left corner.

Maybe h-full is not good enough and it has to be defined just like section above - `min-h-[calc(100vh-64px)]`

**Comment by thedavidprice** [comment]
@KrisCoulson just wanted to get this back on your radar when you have the time.

I've been running tests at http://web.dev/measure/ The "first contentful paint" is the last priority metric we need to resolve.

**Comment by KrisCoulson** [comment]
@thedavidprice I am going to close this PR it didn't actually help the problem but will see if inlining the SVG will work. I saw another closed PR that attempted to fix this.

**Comment by pavelloz** [comment]
If you decide to inline this image (which is pretty big) i would propose to un-inline those:
image

Those images are far below-the-fold and there is no practical reason to inline them. This operation could offset at least a little bit the performance penalty caused by inlining ~255KB of forest.svg

**Pull request closed without merging**
