### PR TITLE
Optimize images

### PR DESCRIPTION
**Pull request by pavelloz**
Hello,

I took a shot at optimizing both bitmaps and SVGs in the project.
Some of the images are over 50% smaller while (at least to my eye) being visually the same. I used quality 85% on JPEG and maximum quality setting in the software i use to do the optimization. It would be better to add f.e. AVIF variant to take advantage of modern format, but i decided to first try to contribute that part and ask about more work later.

Comparing SVGs is... cumbersome, because there is easy preview before/after in github, but SVGs (especially the ones inlined on homepage) were very heavily unoptimized, so there should be a pretty nice gain in size, and hopefully performance. I hope someone will find time to verify if optimized versions are still up to par with quality expectation.

Thank you and great work :)

---
Status before:
image

### CODE REVIEW

**Comment by pavelloz** [comment]
Wow, netlify previews are nice :) I found some regressions, so stay tuned.

**Comment by pavelloz** [comment]
Now its ready to review :)

**Comment by thedavidprice** [comment]
@pavelloz woah, this is incredible... 🤯 Image optimization was definitely on our "when we can get around to it" list.

Quality across the board looks good to me. Looping in @cannikin @KrisCoulson for final call.

Questions:
- _how_ did you do this? (I assume some bulk image processing?)
- do you have recommendations about webp format vs. jpg or png?

Lastly, it would be a pleasure to have you join us at a future Contributors Meetup:
https://community.redwoodjs.com/t/contributors-meetups-a-next-step-for-redwoodjs-participation/2470

Let me know if you're interested and I'll send the invite! (DM `@thedavidprice` anywhere if you don't hear back from me here)

**Comment by cannikin** [comment]
I ran the profile photos through [ImageOptim](https://imageoptim.com/mac) but didn't want to mess with the SVGs in case we had some custom code in there that would get stripped out. But if everything still looks correct, let's do it!

**Comment by cannikin** [comment]
I ran the profile photos through [ImageOptim](https://imageoptim.com/mac) but didn't want to mess with the SVGs in case we had some custom code in there that would get stripped out. But if everything still looks correct, let's do it!

**Review by cannikin — APPROVED** [review]

**Comment by thedavidprice** [comment]
YOLO

**Comment by pavelloz** [comment]
> how did you do this? (I assume some bulk image processing?)

* Bitmaps -> ImageOptim in insane setting - https://imageoptim.com/mac
image
85% for jpeg is probably too high, but its easier to compress further than restore quality :)


* Bulk SVGs -> svgo CLI - https://www.npmjs.com/package/svgo 
* Critical SVGs (those inlined on homepage) -> https://jakearchibald.github.io/svgomg/ with lower precision (1-3 depending on image, to not degrade quality, eyeballing while tuning)

> do you have recommendations about webp format vs. jpg or png? 

I personally use following scheme:
* `legacy format` (png/jpg) + `avif` for normal use
* `legacy` + `webp` + `avif` for pages that i expect a lot of traffic + traffic from enterprise networks (corporations).

Why? Support is not 100% for avif or webp, so its good to have a fallback that will work everywhere. ( https://caniuse.com/webp https://caniuse.com/avif )

Ive seen lot of websites just outsource this work to a CDN. For example cloudinary (ive used cloudflarein the past and it worked good too, but needs more setup, including DNS) - it serves correct image version depending on support determined by accept header value (read: you dont have to do any html changes, apart from url, somewhere in envs probably, and legacy browsers get legacy image, modern browsers get modern format). 

If image optimization is something that is just easily forgotten while doing important stuff, i would recommend using specialized image delivery CDN, there are many. 

> Lastly, it would be a pleasure to have you join us at a future Contributors Meetup

Sure thing, i'll write you an email :)

PS. Fortunately images are in git, so reverting possible regressions shouldn't be too hard :)

**Comment by thedavidprice** [comment]
@pavelloz Bookmarking your comment forever ✅

Thank you!

Email == received!

**Comment by KrisCoulson** [comment]
@pavelloz Just circling back on this. It looks like this PR did break the adventure SVG. Giant shadow looking circle. 

image

**Comment by pavelloz** [comment]
@KrisCoulson Thank you, PR (hopefully) fixing it: https://github.com/redwoodjs/sprout/pull/41

image

**Pull request merged**
